name: Build container release images
on:
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-image:
    uses: ./.github/workflows/build-container-image.yml
    with:
      platforms: linux/amd64
      use_native_arm64_builder: false
      push_to_images: |
        ghcr.io/mastodon-ml/mastodon
      # Do not use cache when building releases, so apt update is always ran and the release always contain the latest packages
      cache: false
      flavor: |
        latest=false
      tags: |
        type=pep440,pattern={{raw}}
        type=pep440,pattern=v{{major}}.{{minor}}
    secrets: inherit
